### ISSUE TITLE
Switch is not exported from 'react-router-dom'

### ISSUE THREAD

**Issue by brlojam4932** [adrianhajdin/project_cryptoverse#19]
./src/App.js
Attempted import error: 'Switch' is not exported from 'react-router-dom'.

It seems that instead of Switch, it must be Routes now but I have tried that and that is not working either

**Comment by brlojam4932** [comment]
So I guess this is the new way of writing this code:

`function App() {
  return (
    <div className="app">
      <div className="navbar">
        <Navbar />
      </div>
      <div className="main">
        <Layout>
          <div className="routes">
            <Routes>
              <Route path="/" element={<HomePage />}>
                <Route path="/exchanges" element={<Exchanges />} />
                <Route path="/cryptocurrencies" element={<Cryptocurrencies />} />
                <Route path="/crypto/:coinId" element={<CryptoDetails />} />
                <Route path="/news" element={<News />} />
              </Route>
            </Routes>
          </div>
        </Layout>
      </div>
      <div className="footer">
      </div>
    </div>
  );
}`

**Comment by aindriu80** [comment]
React Router V6 is out... you will have to change your code if you want to use it or just install the Version 5 which the author is using.

https://reactrouter.com/docs/en/v6/upgrading/v5

**Comment by brlojam4932** [comment]
Yes, I changed it already, thanks!

**Comment by ParkerM2** [comment]
Worked for me!

**Comment by brlojam4932** [comment]
I actually just reinstalled React-Router-Dom as the version he used, v5.2.1 and it works now but glad to hear you got it to work with the new version
