### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by mrhrifat** [adrianhajdin/project_cryptoverse#28]
I am developing `CryptoDetails.jsx` components. I am getting data from API successfully by
```
const { data, isFetching } = useGetCryptoDetailsQuery(coinId)
console.log(data)
```
and the specific data `history` by
```
console.log(data?.data?.coin.name)
```
The problem is, I can't acces data with
```
const cryptoDetails = data?.data?.coin
console.log(cryptoDetails.name)
```
The 2nd line of avobe code show me
> Uncaught TypeError: Cannot read properties of undefined (reading 'name')

- I think, that means the `cyrptoDetails` can't store the `data?.data?.coin` value. I have tried `let & var` instead of `const`. but didn't get any solution.

**Note-** If I comment out the line 
```
console.log(cryptoDetails.name)
``` 
and do
```
const cryptoDetails = data?.data?.coin
console.log(data?.data?.coin.name)
```
reload the browser, than I got the result as I say before. 
But in case if I do **uncomment** the `console.log(cryptoDetails.name)`  & without any reload, It show the data. But then when I reload  the browser, It show me the error.

#### Code of my Components
- CrytoDetails.jsx
```
import React, { useState } from 'react'
import millify from 'millify'
import HTMLReactParser from 'html-react-parser'
import { useParams } from 'react-router-dom'
import { Row, Col, Typography, Select } from 'antd'
import { MoneyCollectOutlined, DollarCircleOutlined, FundOutlined, ExclamationCircleOutlined, StopOutlined, TrophyOutlined, CheckOutlined, NumberOutlined, ThunderboltOutlined } from '@ant-design/icons';
import { useGetCryptoDetailsQuery } from '../services/cryptoApi'
const { Title, Text } = Typography
const { Option } = Select

const CryptoDetails = () => {
    const { coinId } = useParams()
    const [timeperiod, setTimeperiod] = useState('7d')
    const { data, isFetching } = useGetCryptoDetailsQuery(coinId)

    console.log(data)
    const cryptoDetails = data?.data?.coin
    console.log(data?.data?.coin)
    console.log(cryptoDetails.name)
    console.log(data?.data?.coin.name)


    // const stats = [
    //     { title: 'Price to USD', value: `$ ${cryptoDetails.price && millify(cryptoDetails.price)}`, icon: <DollarCircleOutlined /> },
    //     { title: 'Rank', value: cryptoDetails.rank, icon: <NumberOutlined /> },
    //     { title: '24h Volume', value: `$ ${cryptoDetails.volume && millify(cryptoDetails.volume)}`, icon: <ThunderboltOutlined /> },
    //     { title: 'Market Cap', value: `$ ${cryptoDetails.marketCap && millify(cryptoDetails.marketCap)}`, icon: <DollarCircleOutlined /> },
    //     { title: 'All-time-high(daily avg.)', value: `$ ${millify(cryptoDetails.allTimeHigh.price)}`, icon: <TrophyOutlined /> },
    // ];

    return (
        <Col className='coin-detail-container'>
            <Col className='coin-heading-container'>
                <Title level={2} className='coin-name'>
                    {/* {cryptoDetails.name}({cryptoDetails.slug}) Price */}
                </Title>
                <p>
                    {/* {cryptoDetails.name} live price in US dollars. */}
                    View value statistics,market cap & supply
                </p>
            </Col>
            <Select
                defaultValue='7d'
                className='select-timeperiod'
                placeholder='Select Time Period'
                onChange={value => setTimeperiod(value)}
            >
                {time.map(date =>
                    <Option key={date}>{date}</Option>
                )}
            </Select>
        </Col>
    )
}

export default CryptoDetails
```
I have comment out the `stats` because they can't access `cryptoDetails`

- cryptoApi.js
```
import {
    createApi,
    fetchBaseQuery
} from '@reduxjs/toolkit/query/react'

const baseUrl = 'https://coinranking1.p.rapidapi.com'

const createRequest = url => ({
    url,
    headers: cryptoApiHeaders
})

export const cryptoApi = createApi({
    reducerPath: 'cryptoApi',
    baseQuery: fetchBaseQuery({
        baseUrl
    }),
    endpoints: builder => ({
        getCryptos: builder.query({
            query: count => createRequest(`/coins?limit=${count}`)
        }),
        getCryptoDetails: builder.query({
            query: coinId => createRequest(`/coin/${coinId}`)
        })
    })
})

export const {
    useGetCryptosQuery,
    useGetCryptoDetailsQuery
} = cryptoApi
```
I have remove the `cryptoApiHeaders` because of the API code. But in main code I have it.

- How to solve it.
- What does it mean `data?.data?.coin` 
    - (?.)

**Comment by danhdeng** [comment]
you should use console.log(cryptoDetails?.name) instead of console.log(cryptoDetails.name)

data?.data?.coin use ?. to check if data is not null then access data if data.data is not null then access coin. this is the conditional check to avoid the null error.

**Comment by mrhrifat** [comment]
Why should code have to  the `?.` on `console.log(cryptoDeatils?.name)`. When the data is not `null`.

- Is it because of Synchronous & Asynchronous task between my code & server. The local code `cryptoDetails?.name` check one time before it hit on server & return `undefined` then after completing Asynchronous task with server/api it return the data with `?.`
- If the above condition is right then why it return `error` instead of showing `undefined`

**Comment by danhdeng** [comment]
const { data, isFetching } = useGetCryptoDetailsQuery(coinId)

the react hook had been used here. it works like the component. it will cause the functional component to re-render if the state had been change.

that is why you will not see get error when you try to access the cryptoDeatils.name, but you eventually get the cryptoDeatils?.name working because when the data state is change, then it will trigger the functional component to re-render, 

as a result, you can see the value  of crypotDetails in the console windows

**Comment by mrhrifat** [comment]
I think I need to learn more about Hooks. By the way, Thank you so much!

**Comment by mrhrifat** [comment]
Hey there @danhdeng .
I am having a new problem. I am getting `console.log(cryptoDetails?.description)` data successfully. But whenever I set this it to render, I am having `error` of 
> TypeError: First argument must be a string

1. I have import `html-react-parser` & I do use this 
```
<Title className='coin-details-heading' level={3}>
          What is {cryptoDetails?.name}
         {HTMLReactParser(cryptoDetails?.description)}
</Title>
 ```
I can't get the value.
2. I also try
```
<Title className='coin-details-heading' level={3}>
          What is {cryptoDetails?.name}
         {HTMLReactParser(cryptoDetails?.description && cryptoDetails?.description)}
</Title>
 ```
3. &
```
<Title className='coin-details-heading' level={3}>
          What is {cryptoDetails?.name}
         {HTMLReactParser(cryptoDetails.description && cryptoDetails.description)}
</Title>
 ```
As usual I am getting the all value with `?.` thats why the 3 method is not working. But as I am getting the value with `console.log(cryptoDetails?.description)`
The 1 & 2 don't working.

- **Note:** I am getting value sometimes when I don't reload the browser as my first problem & whenever I reload it show me the  `error` .

**Comment by danhdeng** [comment]
you should try this 
cryptoDetails && {HTMLReactParser( cryptoDetails.description)}

this will make sure that cryptoDetails is not null, then i will call HTMLReactParser to parse the cryptoDetails.description

**Comment by danhdeng** [comment]
or you can use this line to prevent the component rendering
 
if (isFetching ) return (<div>loading....</div>)

please put this line before your return statement

if (isFetching ) return **(<div>loading....</div>)
return (
        <Col className='coin-detail-container'>
            <Col className='coin-heading-container'>
                <Title level={2} className='coin-name'>
                    {/* {cryptoDetails.name}({cryptoDetails.slug}) Price */}
                </Title>
                <p>
                    {/* {cryptoDetails.name} live price in US dollars. */}
                    View value statistics,market cap & supply
                </p>
            </Col>
            <Select
                defaultValue='7d'
                className='select-timeperiod'
                placeholder='Select Time Period'
                onChange={value => setTimeperiod(value)}
            >
                {time.map(date =>
                    <Option key={date}>{date}</Option>
                )}
            </Select>
        </Col>
    )

the isFetching is false after the data loading is complete.

**Comment by mrhrifat** [comment]
I solve this by 
```
{HTMLReactParser(cryptoDetails?.description && cryptoDetails?.description || '')}
```
& I also try your suggested code
```
cryptoDetails && { HTMLReactParser(cryptoDetails.description)}
```
It also works. Thanks one second.

- Now I am having a new problem of showing chart with `react-chartjs-2`
The problem I am getting is
> Error: "category" is not a registered scale.
- I have installed `"react-chartjs-2": "^4.0.0"`

- Code of `LineChart.jsx`
```
import React from 'react'
import { Line } from 'react-chartjs-2'
import { Row, Col, Typography } from 'antd'
const { Title } = Typography

const LineChart = ({ coinHistory, currentPrice, coinName }) => {
    const coinPrice = []
    const coinTimestamp = []
    
    for (let i = 0; i < coinHistory?.data?.history?.length; i += 1) {
        coinPrice.push(coinHistory?.data?.history[i].price);
        coinTimestamp.push(new Date(coinHistory?.data?.history[i].timestamp).toLocaleDateString());
    }

    const data = {
        labels: coinTimestamp,
        datasets: [
            {
                label: 'Price in USD',
                data: coinPrice,
                fill: false,
                backgroundColor: '#0071bd',
                borderColor: '#0071bd'
            }
        ]
    }

    const options = {
        scales: {
            yAxes: [
                {
                    ticks: {
                        beginAtZero: true
                    }
                }
            ]
        }
    }

    return (
        <>
            <Row className='chart-header'>
                <Title level={2} className='chart-title'>
                    {coinName} Price Chart
                </Title>
                <Col className='price-container'>
                    <Title level={5} className='price-change'>
                        {coinHistory?.data?.change}%
                    </Title>
                    <Title level={5} className='current-price'>
                        Current {coinName} Price : $ {currentPrice}
                    </Title>
                </Col>
            </Row>
            <Line data={data} options={options} />
        </>
    )
}

export default LineChart
```

- Code of making request
```
getCryptoHistory: builder.query({
            query: ({
                coinId,
                timePeriod
            }) => createRequest(`/coin/${coinId}/history/${timePeriod}`)
        })
```

- Code of `CryptoDetails.jsx`
   - I have import `LineChart` to it
```
const { data: coinHistory } = useGetCryptoHistoryQuery({ coinId, timePeriod })
```
```
<LineChart coinHistory={coinHistory} currentPrice={cryptoDetails?.price} coinName={cryptoDetails?.name} />
```

- I have try some way to solve it.
- How can I solve it?

**Comment by danhdeng** [comment]
you should have chartjs library installed in your project
then put the following code snippet in the import section

import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

now your LineChart.jsx should look like this


import React from 'react';
import { Line } from 'react-chartjs-2';
import { Col, Row, Typography } from 'antd';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

export const LineChart = ({ coinHistory, currentPrice, coinName }) => {

**Comment by mrhrifat** [comment]
It works. thanks one second. 
- Is it because of version upgrade?
- Is there difference between `react-chart-js` & `chartjs`?

**Comment by mrhrifat** [comment]
I am having a new problem of render data in `Exchanges`. Actually I am getting all data successfully. But all data is showing in 
   `col-6` instead of showing `col-24` 

![image](https://user-images.githubusercontent.com/45077312/144871909-e065d3b2-9727-4779-876e-20e99cfbb73c.png)

- The number 1 2 3 4 have to be in each `col-6` element
- I have created `<Col span={6}></Col>` for each element but it doesn't work properly in parent `<Col span={24}></Col>
- My `render` section code of `Exchanges`
```
<>
            <Row>
                <Col span={6}>Exchanges</Col>
                <Col span={6}>24h Trade Volume</Col>
                <Col span={6}>Markets</Col>
                <Col span={6}>Change</Col>
            </Row>
            <Row>
                {exchangesList && exchangesList.map(exchange => (
                    <Col span={24}>
                        <Collapse accordion>
                            <Panel
                                key={exchange?.id}
                                showArrow={false}
                                header={(
                                    <Row key={exchange?.id}>
                                        {/* <Col span={6}>
                                            <Text><strong>{exchange?.rank}.</strong></Text>
                                            <Avatar className="exchange-image" src={exchange?.iconUrl} />
                                            <Text><strong>{exchange?.name}</strong></Text>
                                        </Col>
                                        <Col span={6}>${millify(exchange?.volume)}</Col>
                                        <Col span={6}>{millify(exchange?.numberOfMarkets)}</Col>
                                        <Col span={6}>{millify(exchange?.marketShare)}%</Col> */}
                                        <Col span={6}>1</Col>
                                        <Col span={6}>2</Col>
                                        <Col span={6}>3</Col>
                                        <Col span={6}>4</Col>
                                    </Row>
                                )}
                            >
                                {/* {HTMLReactParser(exchange?.description && exchange?.description || '')} */}
                            </Panel>

                        </Collapse>
                    </Col>
                ))}
            </Row>
        </>
```

**Comment by mrhrifat** [comment]
I am having a new problem of render data in `Exchanges`. Actually I am getting all data successfully. But all data is showing in 
   `col-6` instead of showing `col-24` 

![image](https://user-images.githubusercontent.com/45077312/144871909-e065d3b2-9727-4779-876e-20e99cfbb73c.png)

- The number 1 2 3 4 have to be in each `col-6` element
- I have created `<Col span={6}></Col>` for each element but it doesn't work properly in parent `<Col span={24}></Col>
- My `render` section code of `Exchanges`
```
<>
            <Row>
                <Col span={6}>Exchanges</Col>
                <Col span={6}>24h Trade Volume</Col>
                <Col span={6}>Markets</Col>
                <Col span={6}>Change</Col>
            </Row>
            <Row>
                {exchangesList && exchangesList.map(exchange => (
                    <Col span={24}>
                        <Collapse accordion>
                            <Panel
                                key={exchange?.id}
                                showArrow={false}
                                header={(
                                    <Row key={exchange?.id}>
                                        <Col span={6}>1</Col>
                                        <Col span={6}>2</Col>
                                        <Col span={6}>3</Col>
                                        <Col span={6}>4</Col>
                                    </Row>
                                )}
                            >
                                {/* {HTMLReactParser(exchange?.description && exchange?.description || '')} */}
                            </Panel>

                        </Collapse>
                    </Col>
                ))}
            </Row>
        </>
```

**Comment by danhdeng** [comment]
> It works. thanks one second.
> 
>     * Is it because of version upgrade?
> 
>     * Is there difference between `react-chart-js` & `chartjs`?
react-chartjs-2 is the react componet of chart.js

https://react-chartjs-2.netlify.app/



I believe it is change due to the version uprade.

you can read more about it on the following link

https://www.chartjs.org/docs/3.3.0/getting-started/integration.html#bundlers-webpack-rollup-etc

**Comment by danhdeng** [comment]
> I am having a new problem of render data in `Exchanges`. Actually I am getting all data successfully. But all data is showing in `col-6` instead of showing `col-24`
> 
> ![image](https://user-images.githubusercontent.com/45077312/144871909-e065d3b2-9727-4779-876e-20e99cfbb73c.png)
> 
>     * The number 1 2 3 4 have to be in each `col-6` element
> 
>     * I have created `<Col span={6}></Col>` for each element but it doesn't work properly in parent `
> 
>     * My `render` section code of `Exchanges`
> 
> 
> ```
> <>
>             <Row>
>                 <Col span={6}>Exchanges</Col>
>                 <Col span={6}>24h Trade Volume</Col>
>                 <Col span={6}>Markets</Col>
>                 <Col span={6}>Change</Col>
>             </Row>
>             <Row>
>                 {exchangesList && exchangesList.map(exchange => (
>                     <Col span={24}>
>                         <Collapse accordion>
>                             <Panel
>                                 key={exchange?.id}
>                                 showArrow={false}
>                                 header={(
>                                     <Row key={exchange?.id}>
>                                         <Col span={6}>1</Col>
>                                         <Col span={6}>2</Col>
>                                         <Col span={6}>3</Col>
>                                         <Col span={6}>4</Col>
>                                     </Row>
>                                 )}
>                             >
>                                 {/* {HTMLReactParser(exchange?.description && exchange?.description || '')} */}
>                             </Panel>
> 
>                         </Collapse>
>                     </Col>
>                 ))}
>             </Row>
>         </>
> ```

i added a css class to app.css file

.header-row {
  display: flex;
  justify-content: space-between;
  width: 100% !important;
}

then add this css class to the row header inside the collapse panel

<Row>
        {exchangesList.map((exchange) => (
          <Col span={24}>
            <Collapse>
              <Panel
                key={exchange.id}
                showArrow={false}
                header={
                  <Row key={exchange.id} **className="header-row"**>
                    <Col type="flex" span={6}>
                      <Text>
                        <strong>{exchange.rank}.</strong>
                      </Text>
                      <Avatar
                        style={{ margin: '0 10px' }}
                        src={exchange.iconUrl}
                      />
                      <Text>
                        <strong>{exchange.name}</strong>
                      </Text>
                    </Col>
                    <Col span={6}>${millify(exchange.volume)}</Col>
                    <Col span={6}>{millify(exchange.numberOfMarkets)}</Col>
                    <Col span={6}>{millify(exchange.marketShare)}%</Col>
                  </Row>
                }
              >
                {HTMLReactParser(exchange.description || '')}
              </Panel>
            </Collapse>
          </Col>
        ))}
      </Row>


please your reference you can check out the exchanges component in my github

https://github.com/danhdeng/react-crypto-app/blob/main/src/components/Exchanges.jsx

**Comment by mrhrifat** [comment]
After conversion direct `url,key` to `process.env.***` I am getting error of `too many request` . It send loop request without showing any data. I have searched your project all are same but can't the problem.
- CryptoApi.js
```js
const cryptoNewsApiHeaders = {
    'x-bingapis-sdk': 'true',
    'x-rapidapi-host': process.env.REACT_APP_NEWS_RAPIDAPI_HOST,
    'x-rapidapi-key': process.env.REACT_APP_CRYPTO_RAPID_API_KEY
}

const baseUrl = process.env.REACT_APP_NEWS_API_URL

const createRequest = url => ({
    url,
    headers: cryptoNewsApiHeaders
})
export const cryptoApi = createApi({
    reducerPath: 'cryptoApi',
    baseQuery: fetchBaseQuery({
        baseUrl
    }),
endpoints:---
})
```
-.env
```
REACT_APP_CRYPTO_RAPID_API_HOST = 'crypto-rapid.p.rapidapi.com'
REACT_APP_CRYPTO_RAPID_API_URL = 'https://coinranking1.p.rapidapi.com'
```

**Comment by mrhrifat** [comment]
It's done. Thank you so much.
