### ISSUE TITLE
My value of line chart is not changing after changing timeperiod

### ISSUE THREAD

**Issue by AshvinjeetSingh** [adrianhajdin/project_cryptoverse#51]
My value of line chart is not changing after changing time period
it is not getting updated with the latest redux state  (Setting the date with previous value only)
Can somebody help with this?

**Comment by sabarinathan145** [comment]
same Issue

**Comment by ToddHCarpenter** [comment]
for (let i = 0; i < coinHistory?.data?.history?.length; i += 1) {
    coinPrice.push(coinHistory?.data?.history[i].price);
    coinTimestamp.push(
      new Date(
        coinHistory?.data?.history[i].timestamp * 1000
      ).toLocaleDateString()
    );
  }
