### ISSUE TITLE
Change is not affecting in line chart values

### ISSUE THREAD

**Issue by AshvinjeetSingh** [adrianhajdin/project_cryptoverse#56]
Values of chart are not changing after changing the time period from dropdown
It is only fetching the first record from redux and displaying that instead of the latest one
Can someone help with this?

**Comment by Fremen1990** [comment]
Hi!

It's not fully true, this API in Free Version have limitations and you can send requests just one time per couple seconds, try to wait 2-3 seconds and it should be refreshed automatically. I spent 1hour with that and in RapidAPI docs there is info about these limitations.

PS my Line chart was not working without additional import: 
import {Chart as ChartJS} from 'chart.js/auto'

Let us know if this is working with a delay like on my version 🙂

**Comment by AshvinjeetSingh** [comment]
Values of the chart are changing but Y axes values are remaining the same 
and date are only coming for 24h  even when my default value is set to 7d
Do you have any idea regarding this?

**Comment by ricky-antonio** [comment]
@AshvinjeetSingh 
update you api request url, should be 

createRequest(`/coin/${coinId}/history?timePeriod=${timePeriod}`)

**Comment by AshvinjeetSingh** [comment]
It is working now @ricky-antonio 
thanks for the solution
