### ISSUE TITLE
Error: GET https://coinranking1.p.rapidapi.com/coins?limit=10 410 (Gone)

### ISSUE THREAD

**Issue by Pineapple-1** [adrianhajdin/project_cryptoverse#57]
when you send a get request for coins app crashes due to this error can someone help. I cloned this project still same error :(

**Comment by vedanksingh** [comment]
> when you send a get request for coins app crashes due to this error can someone help. I cloned this project still same error :(


Share you Error screenshot

**Comment by Pineapple-1** [comment]
> > when you send a get request for coins app crashes due to this error can someone help. I cloned this project still same error :(
> 
> Share your Errors screenshot
Home page 
![image](https://user-images.githubusercontent.com/54353428/152636650-e5176c05-3fe9-414f-8712-4f875167e574.png)
console
![image](https://user-images.githubusercontent.com/54353428/152636664-f7077d30-9386-44c0-afb2-fd691cbfa17b.png)

**Comment by vedanksingh** [comment]
Brother u have tk download the updated code. You have use new rapidapi.jsx and new .env

**Comment by Pineapple-1** [comment]
@vedanksingh where can i find the updated code?

**Comment by vedanksingh** [comment]
In code brother in this repository only go and check he has updated the code after 1 jan 2022

**Comment by Pineapple-1** [comment]
updated code is also not working :(

**Comment by vedanksingh** [comment]
> > > when you send a get request for coins app crashes due to this error can someone help. I cloned this project still same error :(
> > 
> > Share your Errors screenshot
> Home page 
> ![image](https://user-images.githubusercontent.com/54353428/152636650-e5176c05-3fe9-414f-8712-4f875167e574.png)
> console
> ![image](https://user-images.githubusercontent.com/54353428/152636664-f7077d30-9386-44c0-afb2-fd691cbfa17b.png)
> 
> 

See he has updated 3 4 files cryptodetails, cryptocurrencies, rapidapi, .env
All these he have updates u can se there all the 1month ago updates files u have to replace just go and replace it but copying

**Comment by Meet0037** [comment]
> updated code is also not working :(

In my case also did not work with the same error. did you find the issue?
