### ISSUE TITLE
getCryptos query is not fetching any data anymore

### ISSUE THREAD

**Issue by jpvision1** [adrianhajdin/project_cryptoverse#65]
Hi all,
I now also have to ask a question about RapidApi. I am about to get the first query "getCryptos" running. But no matter what I try, the console.log always shows "undefined". I have done all updates to v2 and even copied some code from here. I've gotten to the point where I can say that the following code doesn't seem to work properly:

`getCryptos: builder.query({
            query: (count) => createRequest(`/coins?limit=${count}`)
        })`

Can anyone help here? I have also update my key in the env file ofc.
<img width="1849" alt="Bildschirmfoto 2022-02-16 um 00 40 49" src="https://user-images.githubusercontent.com/99771554/154168494-f907af2f-d8de-4219-a864-64c0292d21cb.png">
<img width="593" alt="Bildschirmfoto 2022-02-16 um 00 39 21" src="https://user-images.githubusercontent.com/99771554/154168404-bc3aba43-dcce-4dde-9491-734d2528e87e.png">
<img width="830" alt="Bildschirmfoto 2022-02-16 um 00 39 03" src="https://user-images.githubusercontent.com/99771554/154168410-b983e2ff-7758-4159-a7ea-7015845de9bd.png">
<img width="830" alt="Bildschirmfoto 2022-02-16 um 00 38 52" src="https://user-images.githubusercontent.com/99771554/154168418-f5b615cf-256e-4d57-b59b-bc6f0ac516e4.png">

**Comment by fuddin95** [comment]
I am having the same problem,

**Comment by josemon85** [comment]
Check your URL in the env variables(REACT_APP_CRYPTO_API_URL). I had something like  https://coinranking1.p.rapidapi.com/coins/coins so the endpoint is duplicated, because I copy pasted the code from Rapid API orignally.

**Comment by jpvision1** [comment]
It was not a problem but a mistake on my part. Between minute 45 and 1:05 just make sure you watch and check the website on the homepage and not on Cryptocurrencies. It's a bug in the "count" logic, which Adrian fixes in 1:04h from the video and then the Cryptocurrencies page also loads again without error. 
Since the API codes are interrelated everywhere, copying individual code modules doesn't do much either. 
So if you get an error, just keep going and it should resolve itself. Of course you still have to update to v2 of rapidapi.
