### ISSUE TITLE
rendering a router inside router?

### ISSUE THREAD

**Issue by galpodlipnik1** [adrianhajdin/project_cryptoverse#66]
Error: You cannot render a <Router> inside another <Router>. You should never have more than one in your app. Fix?
![image_2022-02-21_031305](https://user-images.githubusercontent.com/69755435/154877829-277e2eaa-6e21-4dcc-aba4-1a4f9994a833.png)

**Comment by pratham2105** [comment]
In this tutorial he uses the previous version of react-router-dom so have two options first one is to use the previous version or google (you can also check youtube) version 6 react-router-dom changes.
