### ISSUE TITLE
useGetCryptosDetailsQuery is not a function

### ISSUE THREAD

**Issue by Grigormrd** [adrianhajdin/project_cryptoverse#78]
I get following error in the console:

![Screenshot 2022-06-03 183536](https://user-images.githubusercontent.com/67270852/171907852-79353557-32ad-417c-9050-534faf95ccb4.png)

When I am trying to get the data of a coin

![image](https://user-images.githubusercontent.com/67270852/171908022-bb4f1ad2-047f-4c0c-87e2-2ddadc129f5e.png)

**Comment by NaNaFoNo** [comment]
Did you check your naming in the cryptoApi.js. I assume you have a typo in useGetCryptoDetailsQuery, you are importing useGetCrypto**s**DetailsQuery.

**Comment by Grigormrd** [comment]
> Did you check your naming in the cryptoApi.js. I assume you have a typo in useGetCryptoDetailsQuery, you are importing useGetCrypto**s**DetailsQuery.

I have removed the s in Cryptos everywhere in the function and now it works. Can you explain to me why? I can actually name the function whatever I want, can't I?
